### ISSUE TITLE
运行main.py时报错

### ISSUE THREAD

**Issue by lovepeacee** [yazhuo-wyze/imaotai#21]
如题:
好像是因为接口问题,接口返回的数据是xml,但是代码里边是用json做的解析
`~/maotao python main.py

07/07/2023 01:53:46 AM  process.py : WARNING  get_current_session_id : params : 1688688000000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/index/session/get/1688688000000</Resource><RequestId>ZPJC3T8EJ2KEXKLC</RequestId><HostId>21LCYOXSVN5Z91EV</HostId></Error>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/maotao/main.py", line 15, in <module>
    process.get_current_session_id()
  File "/root/maotao/process.py", line 109, in get_current_session_id
    current_session_id = responses.json()['data']['sessionId']
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by lovepeacee** [comment]
找到原因了,是因为服务器时间不对导致的
