### ISSUE TITLE
有这个报错

### ISSUE THREAD

**Issue by yancong001** [yazhuo-wyze/imaotai#26]
07/26/2023 04:32:14 AM  process.py : WARNING  get_current_session_id : params : 1690329600000, response code : 404, response body : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key></Key><BucketName></BucketName><Resource>/mt-backend/xhr/front/mall/index/session/get/1690329600000</Resource><RequestId>ND1RKY9AXOQTUNM0</RequestId><HostId>PQNV9IS97EKYNP5U</HostId></Error>
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/lib/python3.9/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/ubuntu/miniconda3/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/miniconda3/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/miniconda3/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by yazhuo-wyze** [comment]
计算机时区非东八区。
