### ISSUE TITLE
请问是否支持青龙面板加入？

### ISSUE THREAD

**Issue by guochao00** [yazhuo-wyze/imaotai#4]
这个脚本能放入青龙面板里自动执行吗？这样比较直观一点，难度也小点，不知道如何操作,能否给与指导，谢谢

**Comment by yazhuo-wyze** [comment]
> 这个脚本能放入青龙面板里自动执行吗？这样比较直观一点，难度也小点，不知道如何操作,能否给与指导，谢谢

有一些登录的数据需要进行首次初始化。

**Comment by cjumna** [comment]
如果能在青龙跑，那就方便很多，可以利用jd cookie 进行预约和抢购

**Comment by JohnyWu** [comment]
> 如果能在青龙跑，那就方便很多，可以利用jd cookie 进行预约和抢购

不是很理解，这是imaotao app的申购，和JD 预约抢购啥关系？

**Comment by yazhuo-wyze** [comment]
更新下代码，需要重新登录补全信息。会根据地理位置坐标自动预约本市的产品。

请输入你的位置，例如[小区名称]，为你自动预约附近的门店:军安家园
0 : [地区:内蒙古自治区,位置:内蒙古自治区赤峰市红山区军安家园]
请选择位置序号,重新输入请输入[-]:0
已选择 地区:北京市,[北京市海淀区上地十街]附近的门店
输入手机号[13812341234]:1861164****
输入 [1861164****] 验证码[1234]:1234
是否继续添加账号[Y/N]:n

**Comment by xd-2001** [comment]
作者可以写一个青龙面板的脚本嘛 这样方便

**Comment by JohnyWu** [comment]
青龙面板里添加一个任务直接运行main.py不就行了？程序文件整个打包过去呗？

**Comment by Philae994** [comment]
兄弟们，青龙里Crypto在哪改名字

**Comment by xuxiaohu6** [comment]
青龙面板不可以交互，而且读取的credentials文件位置在root文件夹内，可以把login.py的# home_path = os.path.expanduser("~")
改为home_path = os.path.splitext(os.path.split(os.path.abspath(__file__))[0])[0]，这样会读取当前文件夹内的.imaotai的credentials，不过需要提前在电脑上面运行一下login.py，把生成的credentials拷贝过去。

**Comment by EdmundWong98** [comment]
把代码打包丢到青龙面板的脚本管理里 然后单独运行main.py就好啦 前提是把credentials写好 这样就不用交互了

**Comment by jamesyoung233** [comment]
青龙面板里可以运行啊，都上传上去，依赖安装好，credentials可以命令行运行login.py获取或者本地获取好上传就行了

**Comment by 16sea16** [comment]
> 青龙面板里可以运行啊，都上传上去，依赖安装好，credentials可以命令行运行login.py获取或者本地获取好上传就行了

大佬说详细点！谢谢

**Comment by jayron888** [comment]
大佬你好，按您要求修改，运行提示出错，还请帮忙看下
Traceback (most recent call last):
  File "/ql/data/scripts/imaotai/main.py", line 5, in <module>
    import login
  File "/ql/data/scripts/imaotai/login.py", line 24, in <module>
    path = get_credentials_path()
  File "/ql/data/scripts/imaotai/login.py", line 14, in get_credentials_path
    home_path = os.path.splitext(os.path.split(os.path.abspath(file))[0])[0]
NameError: name 'file' is not defined. Did you mean: 'filter'?

**Comment by 84276616** [comment]
> 

        home_path = os.path.splitext(os.path.split(os.path.abspath(__file__))[0])[0]
